#!/bin/ksh

########################################################################
# TITLE:		Get Oracle Table Information 
# FACILITY:   	Andersen Consulting
#
# PURPOSE:
#         	This script retrieves and displays the Table Name, 
#		Number of Fields,Record Size and Field Names for the 
#		passed in copybook name. 
#			
#
# HISTORY:
#        01/24/95 CG  Initial design
#        01/25/95 MPE Stripped off Labels for output file
########################################################################



####################################################################
#
#	Get input parameters          
#
####################################################################
if [ ! "$1" ]; then
	echo "Must enter CopyBookName as first parameter."
	exit 1
fi

CopyBookName=$1


####################################################################
#
#	get table name          
#
####################################################################
GetTableName ()
{
cat $CopyBookName | awk -F "[().*]+" '
#--------------------------------------
# get line with "CUCLS2" char string
# print Table name
#--------------------------------------
   BEGIN     { TableFound=0 }
   /DCLGEN/  { 
		i=index($0, "(");
		j=index($0, ")");
		Path=substr($0, i+1, j-i-1);
		i=index(Path, ".");
		Name=substr(Path, i+1);
		printf("%s\n", Name);
		TableFound=1;
		exit;
	     }
   END	     { 
		if (TableFound==0) printf("ENTER-TABLE-NAME-HERE\n");
	     }
   '
}

####################################################################
#
#	get lines through period
#
####################################################################
GetLineThroughPeriod ()
{
cat $CopyBookName | awk '
	{
	printf("%s ", $0);
	if (index($0, ".")) printf("\n");
	}
	'
}

####################################################################
#
#	get lines with PIC  
#
####################################################################
GetLinesWithPIC ()
{
GetLineThroughPeriod | awk '
   /PIC /   { 
		i=index($0, "PIC");
		print substr($0, i+3);
	     }
   ' 
}

####################################################################
#
#	XRecsizeNumfields
#
####################################################################
XRecsizeNumfields ()
{
#--------------------------------------------------------
# separate Picture Type (i.e. "X(2)" to "X 2")
#--------------------------------------------------------
GetLinesWithPIC | awk -F "[() ]+" '
   BEGIN            { Size=0; Fields=0; }
   $2 ~ /X/           { 
		      FSize=$3;
		      Size=Size+FSize; 
		      Fields=Fields+1; 

		      if (i=index($0, "OCCURS")) {
		        OccrStr=substr($0, i)
		        split(OccrStr, Array1)
			Times=Array1[2]-1
		        Fields=Fields+Times
		        Size=Size+(Times * FSize)
			}
		    }
   END	            { print Size " " Fields }
   '
}

####################################################################
#
#	NumRecsizeNumfields
#
####################################################################
NumRecsizeNumfields ()
{
GetLinesWithPIC | awk -F "[() ]+" '
   BEGIN            { 
			COMP3_Size=0; COMP3_Fields=0; 
			COMP_Size=0; COMP_Fields=0; 
			ZONE_Size=0; ZONE_Fields=0; 
		    }
   #----------------------------------------------------
   #	GetOccursTimes
   #----------------------------------------------------
   function GetNumbersWithinParenthesis (Line) {
	Size=0;

	i=index(Line, "(");
	if (i==0) return Size;
	Line=substr(Line,i+1);
	split(Line,Array1);
	Size=Size+Array1[1];

	i=index(Line, "(");
	if (i==0) return Size;
	Line=substr(Line,i+1);
	split(Line,Array1);
	Size=Size+Array1[1];

	return Size;
	}
   #----------------------------------------------------
   #	GetOccursTimes
   #----------------------------------------------------
   function GetOccursTimes (Line) {
     	if (i=index(Line, "OCCURS")) {
	        OccrStr=substr(Line, i);
	        split(OccrStr, Array1);
		Times=Array1[2];
		return Times;
		}
	else return 0;
	}
   #------------------------------------------------------------------------
   # for COMP-3 numbers, field size = truncation of picture size / 2 + sign
   #------------------------------------------------------------------------
   /COMP-3/ { 
		      NumSize = GetNumbersWithinParenthesis($0) + 1;	
		      CompSize= int((NumSize+1)/2); 
		      Times = GetOccursTimes($0);

		      if (Times) {
		        COMP3_Fields= COMP3_Fields+Times
		        COMP3_Size= COMP3_Size+(Times * CompSize)
			}
		      else {
			COMP3_Size= COMP3_Size+CompSize; 
		        COMP3_Fields= COMP3_Fields+1;
			}
		    }
   #------------------------------------------------------------------------
   # for COMP numbers, field size = 2 bytes if digits < 5, else 4 bytes
   #------------------------------------------------------------------------
   /COMP[ .]/ 	    { 
		      NumSize = GetNumbersWithinParenthesis($0);	
		      Times = GetOccursTimes($0);

		      if (NumSize < 5) CompSize=2
		      else CompSize=4

		      if (Times) {
		        COMP_Fields= COMP_Fields+Times
		        COMP_Size= COMP_Size+(Times * CompSize)
			}
		      else {
			COMP_Size= COMP_Size+CompSize; 
		        COMP_Fields= COMP_Fields+1;
			}
		    }
   #------------------------------------------------------------------------
   # for COMP numbers, field size = truncation of picture size / 2 
   #------------------------------------------------------------------------
   $2 ~ /9/ && ! /COMP/ { 
		      NumSize = GetNumbersWithinParenthesis($0);	
		      Times = GetOccursTimes($0);

		      i=index($2, "S");
		      if (i==1) NumSize=NumSize+1

		      if (Times) {
		        ZONE_Fields= ZONE_Fields+Times
		        ZONE_Size= ZONE_Size+(Times * NumSize)
			}
		      else {
			ZONE_Size= ZONE_Size+NumSize; 
		        ZONE_Fields= ZONE_Fields+1;
			}
		    }
   #-----------------------------------
   # print totals
   #-----------------------------------
   END	            { 
			print COMP3_Size " " COMP3_Fields 
			print COMP_Size " " COMP_Fields 
			print ZONE_Size " " ZONE_Fields 
		    }
   '
}

####################################################################
#
#	print field names   
#
####################################################################
PrintFieldNames ()
{
#echo "\nField Names:" >> $OutputFileName 

cat $CopyBookName | awk '
#--------------------------------------
# get lines with "PIC" char string
#--------------------------------------
   /PIC /   { 
		FieldName=$2;
		printf("%s\n", FieldName);
	     }
   ' 
}

####################################################################
#
#	PrintRecsizeAndNumfields
#
####################################################################
PrintRecsizeAndNumfields ()
{
TOTSIZE=0
TOTFIELDS=0

XRecsizeNumfields | read RECSIZE NUMFIELDS
TOTSIZE=`expr $TOTSIZE + $RECSIZE`
TOTFIELDS=`expr $TOTFIELDS + $NUMFIELDS`

NumRecsizeNumfields | while read RECSIZE NUMFIELDS
do
	TOTSIZE=`expr $TOTSIZE + $RECSIZE`
	TOTFIELDS=`expr $TOTFIELDS + $NUMFIELDS`
done

echo $TOTFIELDS
echo $TOTSIZE
}

####################################################################
#
#	main
#
####################################################################
Main ()
{
GetTableName
PrintRecsizeAndNumfields
PrintFieldNames
}

Main
