#!/bin/ksh
###########################################################################################
# ScriptName :  dblinks
# Description:  This script shows you where your database tables are pointed to (or local)
#                 Using recursion, this script can trace a synonym to the resultant table
#                 or view (which many times can be 4 or 5 synonyms away).  All options are
#                 described in the DEFAULT DATA area.
#
# Date       Programmer         Action
# --------------------------------------------
# 11/14/99   Chris Rodgers      Original Coding (based on waipt and wiipt scripts)
# 08/13/00   Suresh Pellakur    Increased Table name spacing from 18 to 20 Characters. 
#
###########################################################################################

###############################
#  SET UP DEFAULT DATA
###############################
typeset true=1         # statements evaluating to other-than-0 are true
typeset false=0        # statements evaluating to 0 are false

typeset opt_r=$false   # -r  recurse synonyms until table is found
typeset opt_n=$true    # -n  no recursion, only one level of listings           (DEFAULT)
typeset opt_s="L20"    # -s Spacing     defines spacing for table names - Default is 18
typeset opt_d=$false   # -d  database to operate on (default is userid database)
typeset opt_t=$false   # -t Tbl Tbl ... tables to operate on passed in on the line
                       #       This should be in the format of table names separated by spaces
                       #       and the table name must be text name, like bill_acct
                       #    !!cancels -f option; must be the last option passed!!
typeset opt_f=$false   # -f InputFile   list of tables to operate on
                       #       This should be in the format of one table per line
                       #       and the table name must be text name, like bill_acct
                       #    !!not to be used with the -t option!!

typeset InputFile
#typeset -u DataBase=$(id -un)
typeset -u DataBase=$SW_USER
typeset TableSpacing="${opt_s}"  # specifies width of table text; set to blank for no spacing

###############################
#  EVALUATE PARAMETERS
###############################
while getopts ":rRnNhHs:S:d:D:f:F:tT" opt; do
    case $opt in
      r | R ) opt_r=$true;  opt_n=$false;;
      n | N ) opt_r=$false; opt_n=$true;;

      s | S ) if [[ $OPTARG = +([0-9]) ]]; then
                  if [[ $OPTARG = 0 ]]; then
                      TableSpacing=" "
                  else
                      TableSpacing="L${OPTARG}"
                  fi
              else
                  print "Spacing for Table Names must be numeric (0-99)!!!"
                  print "${OPTARG} is not numeric!!!"
                  return 1
              fi;;

      d | D ) opt_d=$true; DataBase=$OPTARG;;

      f | F ) opt_f=$true; opt_t=$false; InputFile=$OPTARG;;

      t | T ) opt_t=$true; opt_f=$false; break;;

      h | H ) print "usage: ${0##*/} [ [-r|-n] [-d DB] [-s SZ] [-f FN|-t Tbl Tbl...] |-h]"
              print " EX:   ${0##*/} -nd c1_ce2d5                                "
              print " EX:   ${0##*/} -rt sad bill_acct SERVICE_PT so_rdg         "
              print " EX:   ${0##*/} -rs 0 -f MyFileOfTableNames                 "
              print "                                                            "
              print " -r  recurse synonyms until table is found                  "
              print " -n  no recursion, only one level of listings      (DEFAULT)"
              print "                                                            "
              print " -s SZ numeric spacing value for table names (18 is DEFAULT)"
              print "                                                            "
              print " -d DB database to operate on (default is userid database)  "
              print "                                                            "
              print " -f FN list of tables to operate on (listed in file FN)     "
              print "       This should be in the format of one table per line   "
              print "       and the table name must be text name, like bill_acct "
              print "       !!not to be used with the -t option!!                "
              print "                                                            "
              print " -t TBL TBL... tables to operate on (passed in on the line) "
              print "       This should be in the format of Name space Name ...  "
              print "       and the table name must be text name, like bill_acct "
              print "       !!cancels -f option; must be the last option passed!!"
              print "                                                            "
              print " -h  display this help message                              "
              return 1;;

      \? )    print "usage: ${0##*/} [ [-r|-n] [-d DB] [-s SZ] [-f FN|-t Tbl Tbl...] |-h]"
              print " EX:   ${0##*/} -nd c1_ce2d5                                "
              print " EX:   ${0##*/} -rt sad bill_acct SERVICE_PT so_rdg         "
              print " EX:   ${0##*/} -rs 0 -f MyFileOfTableNames                 "
              return 1;;
    esac
done
shift $(($OPTIND - 1))


###############################
#  EVALUATE ORACLE VALUES
###############################
if [[ -z ${SW_USER} ]]; then
    SW_USER=$(id -un)
fi

# loop until we have a good oracle password
typeset reprompt=$true
while (( $reprompt )); do
    {
    sqlplus -s ${SW_USER}/${SW_PASSWORD} <<e_test
        exit;
e_test
    } | grep ERROR >/dev/null
    if (( $? )); then     # Password OK
        reprompt=$false
    else                  # Password bad
        print "\nOracle Password for ${SW_USER} is invalid!!!"
        read SW_PASSWORD?'Enter Oracle Password (or Q to quit): '
        if [[ $SW_PASSWORD = [Qq] ]]; then
            return 1
        fi
        clear
    fi
done


###############################
#  FUNCTIONS
###############################
Get_Local_Tabs () {
    sqlplus -s ${SW_USER}/${SW_PASSWORD} <<eof
        set FEEDBACK OFF
        set PAGESIZE 0
        set HEADING OFF
        col OWNER      FORMAT A10 JUSTIFY RIGHT
        col TABLE_NAME FORMAT A20 
        select OWNER, TABLE_NAME
        from DBA_TABLES
        where OWNER = '${DataBase}';
eof
}

Get_All_Syns () {
    sqlplus -s ${SW_USER}/${SW_PASSWORD} <<eof
        set FEEDBACK OFF
        set PAGESIZE 0
        set HEADING OFF
        col SYNONYM_NAME FORMAT A20 
        col TABLE_OWNER  FORMAT A10 JUSTIFY RIGHT
        col TABLE_NAME   FORMAT A20
        select SYNONYM_NAME, TABLE_OWNER, TABLE_NAME
        from DBA_SYNONYMS
        where OWNER = '${DataBase}'
        order by TABLE_OWNER, SYNONYM_NAME;
eof
}

local_check() {
    typeset -u Owner=$1
    typeset -u TableName=$2
    sqlplus -s ${SW_USER}/${SW_PASSWORD} <<local_check_sql
        SET FEEDBACK OFF
        SET HEADING OFF
        SET PAGESIZE 0
        select TABLE_NAME
        from DBA_TABLES
        where OWNER = '${Owner}'
          and TABLE_NAME = '${TableName}';
        exit;
local_check_sql
}

syn_check() {
    typeset -u Owner=$1
    typeset -u TableName=$2
    sqlplus -s ${SW_USER}/${SW_PASSWORD} <<syn_check_sql
        SET FEEDBACK OFF
        SET HEADING OFF
        SET PAGESIZE 0
        col TABLE_OWNER FORMAT A10
        col TABLE_NAME  FORMAT A20 
        select TABLE_OWNER, TABLE_NAME
        from DBA_SYNONYMS
        where OWNER = '${Owner}'
          and SYNONYM_NAME = '${TableName}';
        exit;
syn_check_sql
}

view_check() {
    typeset -u Owner=$1
    typeset -u TableName=$2
    {
    sqlplus -s ${SW_USER}/${SW_PASSWORD} <<view_check_sql
        SET FEEDBACK OFF
        SET HEADING OFF
        SET PAGESIZE 0
        select VIEW_NAME
        from DBA_VIEWS
        where OWNER = '${Owner}'
          and VIEW_NAME = '${TableName}';
        exit;
view_check_sql
    } | wc -l | read ReturnValue
    return $ReturnValue
}

Follow_Syn () {
    # Recursive function
    typeset -u Owner=$1
    typeset -u Table=$2
    typeset -u Owner2=
    typeset -u Table2=
    typeset -u${TableSpacing} TableTxt=
    local_check $Owner $Table | read Table2
    if [[ $Table = $Table2 ]]; then
        print " -> is local"
    else
        syn_check $Owner $Table | read Owner2 Table2
        if [[ -z $Owner2 ]]; then
            view_check $Owner $Table
            if (( $? )); then
                print " -> is a view"
            else
                print " -> NOT A TABLE, SYNONYM, OR VIEW!!!"
            fi
        else
            TableTxt=$Table2
            print -n    "*  -> ${Owner2}.${TableTxt}"
            Follow_Syn $Owner2 $Table2
        fi
    fi
}

LookUp_Table () {
    typeset -u Owner=$1
    typeset -u Table=$2
    typeset -u Owner2=
    typeset -u Table2=
    typeset -u${TableSpacing} TableTxt=
    local_check $Owner $Table | read Table2
    if [[ $Table = $Table2 ]]; then
        print " is local"
    else
        syn_check $Owner $Table | read Owner2 Table2
        if [[ -z $Owner2 ]]; then
            view_check $Owner $Table
            if (( $? )); then
                print " -> is a view"
            else
                print " -> NOT A TABLE, SYNONYM, OR VIEW!!!"
            fi
        else
            TableTxt=$Table2
            print " -> ${Owner2}.${TableTxt}"
        fi
    fi
}


###############################
#  MAIN
###############################
#print "opt_r=$opt_r \n opt_n=$opt_n \n opt_d=$opt_d \n opt_f=$opt_f \n opt_t=$opt_t"
#print "infile=$InputFile"

if (( $opt_f )); then     # Only process file of table names
    typeset -u Owner=$DataBase
    typeset -u Table
    typeset -u${TableSpacing} TableTxt
    while read -u3 Table; do
        TableTxt=$Table
        print -n "${Owner}.${TableTxt}"
        if (( $opt_r )); then
            Follow_Syn $Owner $Table
        else
            LookUp_Table $Owner $Table
        fi
    done 3<$InputFile

elif (( $opt_t )); then   # Only process passed table names
    typeset -u Owner=$DataBase
    typeset -u Table
    typeset -u${TableSpacing} TableTxt
    shift
    while [[ -n $1 ]]; do
        Table=$1
        TableTxt=$Table
        print -n "${Owner}.${TableTxt}"
        if (( $opt_r )); then
            Follow_Syn $Owner $Table
        else
            LookUp_Table $Owner $Table
        fi
        shift
    done

else                      # Process all local tabs and symonyms
    typeset -u OSyn
    typeset -u${TableSpacing} OSynTxt
    typeset -u OOwner
    typeset -u OTab
    typeset -u${TableSpacing} OTabTxt

    Get_Local_Tabs | while read OOwner OTab; do
        OTabTxt=$OTab
        print    "${OOwner}.${OTabTxt} -> is local"
    done

    Get_All_Syns | while read OSyn OOwner OTab; do
        OSynTxt=$OSyn
        OTabTxt=$OTab
        if (( $opt_r )); then
            print -n "${DataBase}.${OSynTxt} -> ${OOwner}.${OTabTxt}"
            Follow_Syn ${OOwner} ${OTab}
        else
            print    "${DataBase}.${OSynTxt} -> ${OOwner}.${OTabTxt}"
        fi
    done
fi
