#!/bin/ksh

#########################################
# fcpkillt5
# This utility allow users to kill any  #
# Front-End service currently running.  #
#
# Modified 6/14/00 - D. Liddle
# Gets PID from ps command instead of cds.log file
# This insures that is picks the correct process ID.
#########################################

if [ $# -eq 0 ]; then
	echo "Usage: fcpkill <service>"
	exit 1
fi

SERVICE=$1
INST=$FNDINST
PREFIX=`echo $SERVICE | cut -c1-2`
INSTPATH=/css/software/fcp/INST/$INST

################################
# Check Service Name Integrity #
################################

if [ ${SERVICE} = "CUFRL080" ]; then
	echo ""
	echo "Permission Denied"
	echo ""
	exit 1
fi

if [ ${#SERVICE} -ne 7 ]; then
	echo ""
	echo "Service name must be 7 characters (CUXXXXX)"
	echo ""
	exit 1
fi

if [ ${PREFIX} != "CU" ]; then
	echo "" 
	echo "Invalid Service name $SERVICE."
	echo "Service name must be in the form 'CUXXXXX'"
	echo ""
	exit 1
fi

################
# Kill Service #
################

APPID=`grep -e APPLICATION -e PROGRAM -e '^$' $INSTPATH/data/SVCAUTH.DAT | awk '{print $3}' | awk -F"\n" '{RS="";print $2,$1}' | grep $SERVICE | awk '{print $2}'`
if [ ${#APPID} -eq 0 ]; then
	echo
	echo "Invalid Service name $SERVICE."
	echo
	exit 1
fi

#PIDNUM=`grep "started: app=$APPID" $INSTPATH/log/cds.log | tail -l 1 | awk '{print $1}' | tr -d "()"`
#if [ ${#PIDNUM} -eq 0 ]; then
#	echo
#	echo "Service $SERVICE is not currently running in $INST."
#	echo
#	exit 1
#fi

#PID=`ps -ef | grep $PIDNUM | grep $FNDINST | grep -v grep | awk '{print $2}`
#PID=`ps -ef | grep fcp | grep $FNDINST | grep $SERVICE | cut -c 10-15`
#chg by Suresh Pellakur for AIX

PID=`ps -ef | grep fcp | grep $FNDINST | grep $SERVICE | cut -c 10-17` 

if [ ${#PID} -eq 0 ]; then
	echo
	echo "Service $SERVICE is not currently running in $INST."
	echo
	exit 1
fi

echo "Kill service $SERVICE in $INST (y/n)? \c " 
read OK
case $OK in
	[Yy]*)	kill -15 $PID
		echo
		echo "Service $SERVICE has been killed."
		echo
		printf "%-12s%-12s%-12s%-30s\n" $SERVICE $INST `id -nru` "`date`" >> $INSTPATH/log/fcpkill.log
		;;
	[Nn]*)	echo
		echo "Service $SERVICE has not been killed!"
		echo
		;;
esac
