#
# This is a config file for NT port
#

[make]
#    02/06/97 GHOWELL - Replaced hardcode with variable
#                       defined in azvars.h header file
#    IncludeDirectory =  L:\INCLUDE
    IncludeDirectory =  $(INCLUDE_DIR)
#    ResourceDirectory = S:\BITMAPS
[numeric field]
    Justification=Right


