#!/bin/ksh

#############################################################################
#
#	File: backupdb
#
#	Description: It exports a user environment to a flat file 
#
#############################################################################


#------------------------------------------
# FUNCTION: GetManagerPassword
# This function dynamically reads the MGR_PASSWORD
#------------------------------------------
GetManagerPassword()
{
. /css/devtools/common/host/scripts/oracle.ksh >/dev/null 2>&1
} 

GetManagerPassword 


#--------------------------------------------
#	check input arguments
#--------------------------------------------
if [ ! "$1" ]; then
	echo "*** error: missing output filename"
	echo "format: \$ backupdb <output filename> <database area>"
	exit 0
fi

if [ ! "$2" ]; then
	echo "*** error: missing database area"
	echo "format: \$ backupdb <output filename> <database area>"
	exit 0
fi

#--------------------------------------------
#	assign variable values
#--------------------------------------------
FNAME=$1	# file name
FromUserArea=$2	# source database area
TableList=$3    # list of tables to backup

#---------------------------------------------
# build and execute the export file 
#---------------------------------------------
#buffer1=$ORACLE_HOME'/bin/exp dstuser/$MANAGER_PASSWORD '  
PARFILE=~/ze.par
touch $PARFILE
chmod 700 $PARFILE
echo userid=dstuser/$MANAGER_PASSWORD  > $PARFILE

if [[ -n $TableList ]]; then
    echo   'tables='$TableList >> $PARFILE
else
    echo   'owner='$FromUserArea >> $PARFILE
fi
    echo 'file='$FNAME  >> $PARFILE

$ORACLE_HOME/bin/exp parfile=$PARFILE
#print $EXPORT > export_user
#chmod 755 export_user
#eval export_user

rm -f $PARFILE

#----------------------------------------------------------
# change permisions to owner read-write, group read-only
#----------------------------------------------------------
if [ -f $FNAME ]; then
	chmod 644 $FNAME
else
	chmod 644 $FNAME.dmp
fi

GetManagerPassword

