#!/bin/ksh 
###########################################################################################
# ScriptName :  bae_shell - Bill Account Extract Shell
# Description:  This script is an interactive (menu) shell for running BAE scripts for
#               information and maintenance.
#
# Date       Programmer         Action
# --------------------------------------------
# 01/27/99   Chris Rodgers      Original coding
# 03/16/99   Chris Rodgers      Completed version 1.0
# 03/22/99   Chris Rodgers      Version 1.1
#                               Added hard-coded list of databases to check for bill accounts.
# 07/29/99   Tanya McEwen       Added bae_tabs client detection using PROJECT variable
#                               Checked scripts into global area for use by all SolutionWorks
#                               Updated version to 1.2
###########################################################################################

# No options are supported at this time.
# Future options include passing in responses to menus.
#
# Still not done:
#   prompt for database for checking for an account (got enought for's?)
#   delete ranges of accounts
#   delete since date
#
# Future Additions:
#   Maint: Details Stats - reports average, max, and min rows per timestamp.
#   Maint: Extents Rpt - reports number and size of extents taken up by hdr and dtl tabs.
#                        ?? can calc / report free space in table?
#   Maint: redo hdr or dtl table to make smaller with larger extent?
#   Maint: Balance Hdr Dtl - Checks for details without headers and vice versa.

typeset Version="v1.2"
typeset Title="Bill Account Extract Shell  ${Version}"
typeset REPLY
typeset BuffHdrRecs
typeset -R3 cnt2
typeset -i LineCounter
typeset -i LINES=53

unset MORE

######################
# FUNCTION DEFINITIONS
######################


MenuMain() {
  typeset reprompt=true
  while [[ ${reprompt} = true ]]; do
      clear
      print "\n${Title}\n"

      print "Main Menu\n"

      print " 1. Buffer List Menu  - list accounts in the buffer"
      print " 2. Delete Menu       - delete extractions from the buffer"
      print " 3. Tables List Menu  - see which tables are extracted, static, empty, etc"
      print " 4. Maintenance Menu  - misc bae buffer information"
      print "99. Quit\n"

      read REPLY?'Selection: '

      case ${REPLY} in
          1 ) MenuBuffer;;
          2 ) MenuDelete;;
          3 ) MenuTable;;
          4 ) MenuMaint;;

          99 ) reprompt=false ;;

          * ) print "Invalid Option!!!\n"
              read filler?'Press Enter to continue...';;
      esac
  done
}

MenuBuffer() {
  typeset reprompt=true
  while [[ ${reprompt} = true ]]; do
      clear
      print "\n${Title}\n"

      print "Buffer List Menu\n"

      print " 1. List All Accounts by account number"
      print " 2. List All Accounts by account number with rows for each (takes a while)"
      print " 3. List All Accounts by timestamp"
      print " 4. List All Accounts by timestamp with rows for each (takes a while)"
      print " 5. List One Account  with table details"
      print " 6. List One Account  with total number of rows"
      print "99. Return to Main Menu\n"

      read REPLY?'Selection: '

      case ${REPLY} in
          1 ) bae_bl -a | more -d;;
          2 ) bae_bl -ar | more -d;;
          3 ) bae_bl -t | more -d;;
          4 ) bae_bl -tr | more -d;;
          5 ) ListOneLong;;
          6 ) ListOneShort;;
          99 ) reprompt=false ;;
          * ) print "Invalid Option!!!\n"
              read filler?'Press Enter to continue...'
              reprompt=true ;;
      esac
  done
}

MenuDelete() {
  typeset reprompt=true
  while [[ ${reprompt} = true ]]; do
      clear
      print "\n${Title}\n"

      print "Delete Menu\n"

      print " 1. Delete One Account by timestamp"
      print " 2. Delete One Account by account number"
      print " 3. Delete Multiple Accounts (ranges, number of days, etc)"
      print "99. Return to Main Menu\n"

      read REPLY?'Selection: '

      case ${REPLY} in
          1 ) DelOneTS;;
          2 ) DelOneKyBa;;
          3 ) read filler?'Function not available in this version.  Press Enter to continue...';;
          99 ) reprompt=false ;;
          * ) print "Invalid Option!!!\n"
              read filler?'Press Enter to continue...'
              reprompt=true ;;
      esac
  done
}

MenuTable() {
  typeset reprompt=true
  typeset Client
  typeset Options

  if [[ ${PROJECT} = t5am ]]; then
      Client="AM"
  elif [[ ${PROJECT} = t5ppl ]]; then
      Client="PP"
  elif [[ ${PROJECT} = t5nm ]]; then
      Client="NM"
  elif [[ ${PROJECT} = t5me ]]; then
      Client="ME"
  elif [[ ${PROJECT} = t4_ce ]]; then
      Client="CE"
  elif [[ ${PROJECT} = t4_or ]]; then
      Client="OR"
  elif [[ ${PROJECT} = base ]]; then
      Client=""
  fi
    
  while [[ ${reprompt} = true ]]; do
      clear
      print "\n${Title}\n"

      print "Table List Menu\n"

      print " 1. List All Tables with flags (sorted by table name)"
      print " 2. List All Tables with flags (sorted by flag)"
      print " 3. List All Tables for a particular flag (sorted by table name)"
      print " 4. List All Tables for a particular flag (sorted by flag)"
      print "99. Return to Main Menu\n"

      read REPLY?'Selection: '

      case ${REPLY} in
          1 ) bae_tabs -tc "${Client}"
              read filler?'Press Enter to continue...';;
          2 ) bae_tabs -c "${Client}"
              read filler?'Press Enter to continue...';;
          3 ) GetTableFlag
              if [[ ${REPLY} -ne "99" ]]; then
                  bae_tabs ${Options} -tc "${Client}"
                  read filler?'Press Enter to continue...'
              fi;;
          4 ) GetTableFlag
              if [[ ${REPLY} -ne "99" ]]; then
                  bae_tabs ${Options} -c "${Client}"
                  read filler?'Press Enter to continue...'
              fi;;
          99 ) reprompt=false ;;
          * ) print "Invalid Option!!!\n"
              read filler?'Press Enter to continue...'
              reprompt=true ;;
      esac
  done
}

MenuMaint() {
  typeset reprompt=true
  while [[ ${reprompt} = true ]]; do
      clear
      print "\n${Title}\n"

      print "Maintenance Menu\n"

      print " 1. List row counts for buffer detail and header tables"
      print " 2. Delete buffer contents for one table of a particular account"
      print " 3. See if an account exists in a database"
      print "99. Return to Main Menu\n"

      read REPLY?'Selection: '

      case ${REPLY} in
          1 ) BufferHdrCount | read HdrCnt
              print "\n\nBuffer Header Table has ${HdrCnt} records."
              BufferDtlCount | read DtlCnt
              print "Buffer Detail Table has ${DtlCnt} records.\n"
              read filler?'Press Enter to continue...';;
          2 ) DelOneTab;;
          3 ) CheckKyBa;;
          99 ) reprompt=false ;;
          * ) print "Invalid Option!!!\n"
              read filler?'Press Enter to continue...';;
      esac
  done
}

ListOneLong() {
  typeset reprompt=true
  while [[ ${reprompt} = true ]]; do
      ListBufferHdr -a
      print "999: CANCEL COMMAND\n"
      read REPLY?'Select an account or option from above: '

      case ${REPLY} in
               999 ) reprompt=false ;;
          +([0-9]) ) if ((REPLY > cnt)); then
                         print "Invalid Option!!!\n"
                         read filler?'Press Enter to continue...'
                         reprompt=true
                     else
                         clear
                         bae_rc -t ${BHT[${REPLY}]} | more -d
                         reprompt=false 
                     fi;;
                 * ) print "Invalid Option!!!\n"
                     read filler?'Press Enter to continue...'
                     reprompt=true ;;
      esac
  done
}

ListOneShort() {
  typeset reprompt=true
  while [[ ${reprompt} = true ]]; do
      ListBufferHdr -a
      print "999: CANCEL COMMAND\n"
      read REPLY?'Select an account or option from above: '

      case ${REPLY} in
               999 ) reprompt=false ;;
          +([0-9]) ) if ((REPLY > cnt)); then
                         print "Invalid Option!!!\n"
                         read filler?'Press Enter to continue...'
                         reprompt=true
                     else
                         clear
                         bae_rc -st ${BHT[${REPLY}]} | more -d
                         reprompt=false 
                     fi;;
                 * ) print "Invalid Option!!!\n"
                     read filler?'Press Enter to continue...'
                     reprompt=true ;;
      esac
  done
}

ListBufferHdr()  {
  typeset Option="$1"
    
  bae_bl -q ${Option} | {
      let cnt=0
      while read BuffHdrAcct BuffHdrTS ; do
          let cnt=cnt+1
          BHA[${cnt}]=${BuffHdrAcct}
          BHT[${cnt}]=${BuffHdrTS}
      done 
  }

  let TermLines=$((LINES - 3))
  let cnt2=0
  clear
  print "\n${Title}\n"
  print "Buffer Listing\n"
  let LineCounter=4

  while ((cnt2 < cnt)); do
      let cnt2=cnt2+1
      if ((LineCounter > TermLines)); then
          read filler?'Press Enter to Continue List...'
          clear
          print "\n${Title}\n"
          print "Buffer Listing\n"
          let LineCounter=4
      fi
      let LineCounter=LineCounter+1
      print "${cnt2}:  ${BHA[${cnt2}]}  ${BHT[${cnt2}]}"
  done
} 

ListBufferDtlTabs() {
  TimeStamp="$1"
  BufferDtlTabList ${TimeStamp} | {
      let cnt=0
      while read BuffDtlTab BuffDtlCnt ; do
          let cnt=cnt+1
          BDT[${cnt}]=${BuffDtlTab}
          BDC[${cnt}]=${BuffDtlCnt}
      done 
  }

  let TermLines=$((LINES - 3))
  let cnt2=0
  clear
  print "\n${Title}\n"
  print "Buffer Table Listing For Timestamp ${TimeStamp}\n"
  let LineCounter=4

  while ((cnt2 < cnt)); do
      let cnt2=cnt2+1
      if ((LineCounter > TermLines)); then
          read filler?'Press Enter to Continue List...'
          clear
          print "\n${Title}\n"
          print "Buffer Table Listing For Timestamp ${TimeStamp}\n"
          let LineCounter=4
      fi
      let LineCounter=LineCounter+1
      print "${cnt2}:  ${BDT[${cnt2}]}  ${BDC[${cnt2}]}"
  done
}

BufferHdrCount() {
sqlplus -s acct_xtract/acct_xtract <<EOIBufferHdrCount
SET FEEDBACK OFF
SET HEADING OFF
SET PAGESIZE 0
select count(*)
from extract_ld_hdr ;
exit;
EOIBufferHdrCount
}

BufferDtlCount() {
sqlplus -s acct_xtract/acct_xtract <<EOIBufferDtlCount
SET FEEDBACK OFF
SET HEADING OFF
SET PAGESIZE 0
select count(*)
from extract_ld_dtl ;
exit;
EOIBufferDtlCount
}

BufferDtlTabList() {
  TimeStamp="$1"
sqlplus -s acct_xtract/acct_xtract <<EOIBufferDtlTabList
SET FEEDBACK OFF
SET HEADING OFF
SET PAGESIZE 0
select BAT_TBL_ID, count(*)
from extract_ld_dtl
where arch_oth_ts_dt_tm = '${TimeStamp}'
group by BAT_TBL_ID;
exit;
EOIBufferDtlTabList
}


DelOneTab() {
  typeset TimeStamp
  typeset TableName

  typeset reprompt=true
  typeset CancelReq=false
  while [[ ${reprompt} = true && ${CancelReq} = false ]]; do
      ListBufferHdr -t
      print "999: CANCEL COMMAND\n"
      read REPLY?'Select an account or option from above: '

      case ${REPLY} in
               999 ) CancelReq=true;;
          +([0-9]) ) if ((REPLY > cnt)); then
                         print "Invalid Option!!!\n"
                         read filler?'Press Enter to continue...'
                         reprompt=true
                     else
                         TimeStamp=${BHT[${REPLY}]}
                         reprompt=false 
                     fi;;
                 * ) print "Invalid Option!!!\n"
                     read filler?'Press Enter to continue...'
                     reprompt=true ;;
      esac
  done

  reprompt=true
  while [[ ${reprompt} = true && ${CancelReq} = false ]]; do
      ListBufferDtlTabs ${TimeStamp}
      print "999: CANCEL COMMAND\n"
      read REPLY?'Select a table or option from above: '

      case ${REPLY} in
               999 ) CancelReq=true;;
          +([0-9]) ) if ((REPLY > cnt)); then
                         print "Invalid Option!!!\n"
                         read filler?'Press Enter to continue...'
                         reprompt=true
                     else
                         TableName=${BDT[${REPLY}]}
                         print -n "\n"
                         bae_del_tab -c ${TimeStamp} ${TableName}
                         print -n "\n"
                         read REPLY?'DELETE BUFFER TABLE CONTENTS: ARE YOU SURE??? (Y/N) '
                         if [[ ${REPLY} = Y || ${REPLY} = y ]]; then
                             print -n "\n"
                             bae_del_tab ${TimeStamp} ${TableName}
                             read filler?'Press Enter to continue...'
                         else
                             print -n "\nCOMMAND ABORTED!!!\n"
                             read filler?'Press Enter to continue...'
                         fi
                         reprompt=false 
                     fi;;
                 * ) print "Invalid Option!!!\n"
                     read filler?'Press Enter to continue...'
                     reprompt=true ;;
      esac
  done
}

Ck_KyBa() {
  typeset KyBa="$1"
  typeset CkDB="$2"
sqlplus -s ${SW_USER}/${SW_PASSWORD} <<EOICk_KyBa
SET FEEDBACK OFF
SET HEADING OFF
SET PAGESIZE 0
select count(*) from ${CkDB}sad where ky_ba = ${KyBa};
exit;
EOICk_KyBa
}

CheckKyBa() {
  typeset KyBa
  typeset CkDB

#future enhancement: prompt for database through ini file or sql list of databases available.
#  for now, use user's current database.

  typeset reprompt=true
  while [[ ${reprompt} = true ]]; do
      ListBufferHdr -a
      print "999: CANCEL COMMAND\n"
      read REPLY?'Select an account or option from above: '

      case ${REPLY} in
               999 ) reprompt=false;;
          +([0-9]) ) if ((REPLY > cnt)); then
                         print "Invalid Option!!!\n"
                         read filler?'Press Enter to continue...'
                         reprompt=true
                     else
                         KyBa=${BHA[${REPLY}]}

                         while [[ ${reprompt} = true ]]; do
                             CancelCmd=false
                             clear
                             print "\n${Title}\n"

                             print "See if an account exists in a database\n"

                             print " 1. Choose database name yourself (i.e. C1_CED1BB)"
                             print " 2. ${SW_USER} (your local database)"
                             print "99. Cancel Command\n"

                             read REPLY?'Select a database or option from above: '

                             case ${REPLY} in
                                 1 )  print "Enter database name: "; read DBName; 
                                      CkDB="${DBName}.";  reprompt=false ;;
                                 2 )  CkDB="${SW_USER}."; reprompt=false ;;
                                 99 ) CkDB=" ";           reprompt=false ;  CancelCmd=true;;
                                 * ) print "Invalid Option!!!\n"
                                     read filler?'Press Enter to continue...';;
                             esac
                         done

                         if [[ ${CancelCmd} = false ]]; then
                             Ck_KyBa ${KyBa} ${CkDB} | read YN
                             if [[ ${YN} = 0 ]]; then
                                 print "\nThe account ${KyBa} does not appear in the database ${CkDB}SAD table.\n"
                             else
                                 print "\nThe account ${KyBa} exists in the ${CkDB}SAD table ${YN} time(s).\n"
                             fi
                             read filler?'Press Enter to continue...'
                         fi
                     fi;;
                 * ) print "Invalid Option!!!\n"
                     read filler?'Press Enter to continue...'
                     reprompt=true ;;
      esac
  done
}

GetTableFlag() {
  typeset reprompt=true
  while [[ ${reprompt} = true ]]; do
      clear
      print "\n${Title}\n"

      print "BAE Table Flags:"
      print "[Please let your primary BAE contact know if you have questions on"
      print "these flags, see a table missing, or think a flag needs to be changed]\n"

      print " 1. A - active tables  (extracted)"
      print " 2. E - empty tables   (not extracted)"
      print " 3. P - problem tables (not extracted)"
      print " 4. S - static tables  (not extracted)"
      print " 5. E and S"
      print " 6. A E and S"
      print " 7. E P and S"
      print " 8. A E P and S"
      print "99. Return to Main Menu\n"

      read REPLY?'Selection: '

      case ${REPLY} in
          1 ) Options="-a";   reprompt=false ;;
          2 ) Options="-e";   reprompt=false ;;
          3 ) Options="-p";   reprompt=false ;;
          4 ) Options="-s";   reprompt=false ;;
          5 ) Options="-es";  reprompt=false ;;
          6 ) Options="-aes"; reprompt=false ;;
          7 ) Options="-eps"; reprompt=false ;;
          8 ) Options="";     reprompt=false ;;
          99 ) reprompt=false ;;
          * ) print "Invalid Option!!!\n"
              read filler?'Press Enter to continue...'
      esac
  done
}

DelOneTS() {
  print " reached DelOneTS\n" 
  typeset  TimeStamp
  print " reached DelOneTS 2..\n"
  typeset  KyBa
  typeset reprompt=true
  print " reached DelOneTS 3..\n"
  typeset CancelReq=false
  while [[ ${reprompt} = true && ${CancelReq} = false ]]; do
      print " reached DelOneTS 4..\n"
      ListBufferHdr -t
      print "999: CANCEL COMMAND\n"
      read REPLY?'Select an account or option from above: '

      case ${REPLY} in
               999 ) CancelReq=true;;
          +([0-9]) ) if ((REPLY > cnt)); then
                         print "Invalid Option!!!\n"
                         read filler?'Press Enter to continue...'
                         reprompt=true
                     else
                         TimeStamp=${BHT[${REPLY}]}
                         KyBa=${BHA[${REPLY}]}
                         reprompt=false 
                     fi;;
                 * ) print "Invalid Option!!!\n"
                     read filler?'Press Enter to continue...'
                     reprompt=true ;;
      esac
  done

  if [[ $CancelReq = false ]]; then
      print "\nDelete Timestamp: ${TimeStamp}, Ky_Ba: ${KyBa}\n"
      read REPLY?'DELETE BUFFER CONTENTS: ARE YOU SURE??? (Y/N) '
      if [[ ${REPLY} = Y || ${REPLY} = y ]]; then
          print -n "\n"
          bae_del -t ${TimeStamp}
          read filler?'Press Enter to continue...'
      else
          print -n "\nCOMMAND ABORTED!!!\n"
          read filler?'Press Enter to continue...'
      fi
  else
      print -n "\nCOMMAND ABORTED!!!\n"
      read filler?'Press Enter to continue...'
  fi
}

DelOneKyBa() {
	
  typeset TimeStamp
  typeset KyBa

  typeset reprompt=true
  typeset CancelReq=false
  while [[ ${reprompt} = true && ${CancelReq} = false ]]; do
      ListBufferHdr -a
      print "999: CANCEL COMMAND\n"
      read REPLY?'Select an account or option from above: '

      case ${REPLY} in
               999 ) CancelReq=true;;
          +([0-9]) ) if ((REPLY > cnt)); then
                         print "Invalid Option!!!\n"
                         read filler?'Press Enter to continue...'
                         reprompt=true
                     else
                         TimeStamp=${BHT[${REPLY}]}
                         KyBa=${BHA[${REPLY}]}
                         reprompt=false 
                     fi;;
                 * ) print "Invalid Option!!!\n"
                     read filler?'Press Enter to continue...'
                     reprompt=true ;;
      esac
  done

  if [[ $CancelReq = false ]]; then
      print "\nDelete ALL TIMESTAMPS for Ky_Ba: ${KyBa}\n"
      read REPLY?'DELETE BUFFER CONTENTS: ARE YOU SURE??? (Y/N) '
      if [[ ${REPLY} = Y || ${REPLY} = y ]]; then
          print -n "\n"
          bae_del -a ${KyBa}
          read filler?'Press Enter to continue...'
      else
          print -n "\nCOMMAND ABORTED!!!\n"
          read filler?'Press Enter to continue...'
      fi
  else
      print -n "\nCOMMAND ABORTED!!!\n"
      read filler?'Press Enter to continue...'
  fi
}

####################
# MAIN SCRIPT
####################

MenuMain
