#!/bin/ksh
#

print "Calculating...  "

typeset InFile=$1
typeset TmpFile=/var/tmp/bs$$
typeset ReturnLine

sed -e 's/^ *01 /      *01 /' ${InFile} >${TmpFile}
cd /var/tmp
bitesize.ksh ${TmpFile} 2>/dev/null | tail -1 | read ReturnLine
rm -f ${TmpFile}
rm -f SWBS001.*
cd -

if print "${ReturnLine}" | grep Error ; then
    print "ERROR compiling or running bitesize.\nRun bitesize <copybook> for details."
else
    print "The size of copybook ${InFile} is ${ReturnLine} bytes."
fi
