#!/bin/ksh 

#######################################################
#
#	File: c1ungen 
#
#	Description: generates a cobol program to unload
#		     Oracle tables
#
#
#######################################################

#------------------------------------------------------
#	Init
#------------------------------------------------------
Init ()
{
### Template Program ###
PTEMPLATE="$BASE_TOOL/common/host/data/C1UN0000.pco"
echo "Template Program [$PTEMPLATE]: \c"
read NEW_PTEMPLATE
case "$NEW_PTEMPLATE" in
	"")     PTEMPLATE="$PTEMPLATE" ;;
	*)      PTEMPLATE="$NEW_PTEMPLATE" ;;
esac
export PTEMPLATE

### CopyBook Directory ###
CPYDIR="$HOST_APPL/source/copy/table"
echo "Copybook Directory [$CPYDIR]: \c"
read NEW_CPYDIR
case "$NEW_CPYDIR" in
	"")     CPYDIR="$CPYDIR" ;;
	*)      CPYDIR="$NEW_CPYDIR" ;;
esac
export CPYDIR

### CopyBook ###
COPYBOOK="CU10TB27"
echo "Copybook Name [$COPYBOOK]: \c"
read NEW_COPYBOOK
case "$NEW_COPYBOOK" in
	"")     COPYBOOK="$COPYBOOK" ;;
	*)      COPYBOOK="$NEW_COPYBOOK" ;;
esac
export COPYBOOK
}

#------------------------------------------------------
#	Main
#------------------------------------------------------
Main ()
{
Init
c1ungenp $PTEMPLATE $CPYDIR/$COPYBOOK
rm c1undata.txt 1> /dev/null 2> /dev/null
}

Main
