#!/bin/ksh
#
#   change_oracle_password
#
#   Author: Shilpa Patel
#
#   Modified: Jake Ruttenberg
#      - queries database for system password
#      - does not allow a user to create a password larger than 8 characters
#        to correspond with a CSS limitation.
#   Modified: Greg Augustine 
#      - removed query database for system password - user can change own password
#      - reduced changes to swt4o8 and swt5o8 as they are only instances now

#------------------------------------------------------------------
#   change password
#-------------------------------------------------------------------
ChangePassword()
{
clear
echo "********************************************************************"
echo "********************************************************************"
echo "        WELCOME TO THE ORACLE PASSWORD CHANGE UTILITY               "
echo '\n'
echo "         THIS UTILITY CHANGES YOUR ORACLE PASSWORDS                 "
echo "            IN THE SWT4O8 and SWT5O8 INSTANCES             "
echo "********************************************************************"
echo "********************************************************************"
echo '\n'
echo "***************************WARNING**********************************"
echo "You must have your SW_USER and SW_PASSWORD environment variables set"
echo "to execute this script!!!!                                          "
sleep 3
/bin/tput clear
echo "Please enter your Oracle User Id :                  \c"
read USERID
echo "Please enter your current oracle password :         \c"
stty -echo
read CURRPASS
/bin/tput clear
echo "Getting system environment information....."
sleep 2
SET_PASS=0
/bin/tput clear
echo "Verifying your current password............"
sleep 2
if [[ -z "`sqlplus -s $USERID/$CURRPASS < /dev/null`" ]] then
  until [[ $SET_PASS = "3" ]]
  do
       echo "Please enter your new Oracle Password :             \c"
       stty -echo
       read NEWPASS
       stty echo
       echo 
       echo "Please re-enter the new password for verification : \c"
       stty -echo
       read NEWPASS1
       stty echo
       echo 
       if [[ "${NEWPASS}" = "${NEWPASS1}" ]] then
          echo $NEWPASS | awk '
BEGIN {
}
{
  if ( length($0) > 8 )
  {
     print substr($0,1,8);
  }
  else
  {
     print;
  }
} ' > tmp.sql
          cat tmp.sql | read NEWPASS2 DUMMY
          SET_PASS=3
          echo '\n'
          echo "************************WARNING**************************"
          echo "All passwords longer than 8 characters will be truncated."
sleep 2
/bin/tput clear
          echo "changing password, please wait"
          sqlplus -s  $USERID/$CURRPASS@swt5o8 <<END2
	  alter user $USERID identified by $NEWPASS2;
		    exit;
END2
          sqlplus -s  $USERID/$CURRPASS@swt4o8 <<END3
          alter user $USERID identified by $NEWPASS2;
          exit;
END3
          rm tmp.sql
      else
          echo '\n'
          echo "New password and Verification password did not match."
          echo '\n'
          SET_PASS=`expr $SET_PASS + 1`
      fi
    done
else
      echo "Invalid oracle ID or Password."
fi
}

#-------------------------------
#   Main
#-------------------------------
Main()
{
ChangePassword
}
Main
