#!/bin/ksh

#############################################################################
#
#	File: copytb
#
#	Description: It copies a table from one database/owner to another
#
#############################################################################

#--------------------------------------------
#	check input arguments
#--------------------------------------------
if [ ! "$1" ]; then
	echo "\n*** error: missing table name"
	echo "format: \$ copytb <tablename> <source area> <object area>\n"
	exit 0
fi

if [ ! "$2" ]; then
	echo "\n*** error: missing source area"
	echo "format: \$ copytb <tablename> <source area> <object area>\n"
	exit 0
fi

if [ ! "$3" ]; then
	echo "\n*** error: missing object area"
	echo "format: \$ copytb <tablename> <source area> <object area>\n"
	exit 0
fi

#--------------------------------------------
#	assign variable values
#--------------------------------------------
GetManagerPassword()
{
. /css/devtools/common/host/scripts/oracle.ksh >/dev/null 2>&1
}

GetManagerPassword

TableName=$1		# table name is supplied as argument 1

FromUserId=$2
ToUserID=$3

if [[ $SW_USER != $ToUserID && $SW_USER != 'dstuser' ]]; then
	echo "Sorry, you are not authorized to copy outside your SW_USER"
	exit
fi

FromDatabase=$ORACLE_SID	# database link

#---------------------------------------------
#	function to copy a table 
#---------------------------------------------
CopyTable ()
{
TempFile=~/ztdm.tmp

sqlplus $SW_USER/$SW_PASSWORD <<END
drop table $ToUserID.$TableName;
drop synonym $ToUserID.$TableName;
drop sequence $ToUserID.$TableName;
END

echo "From working area $FromUserId"
touch ~/ze.par
chmod 700 ~/ze.par
export PARFILE=~/ze.par

echo userid=dstuser/$MANAGER_PASSWORD >> $PARFILE
echo file=$TempFile >> $PARFILE
echo compress=n  >> $PARFILE
echo tables=$FromUserId.$TableName >> $PARFILE
# echo log=/home/fcp/$TableName.explog >> $PARFILE

#cp $PARFILE $PARFILE.exp

echo "$ORACLE_HOME/bin/exp parfile=$PARFILE"
$ORACLE_HOME/bin/exp parfile=$PARFILE

echo userid=dstuser/$MANAGER_PASSWORD > $PARFILE
echo file=$TempFile >> $PARFILE
echo fromuser=$FromUserId touser=$ToUserID >> $PARFILE
# echo log=/home/fcp/$TableName.implog >> $PARFILE

echo "To working area $ToUserID"
echo "$ORACLE_HOME/bin/imp parfile=$PARFILE"

$ORACLE_HOME/bin/imp parfile=$PARFILE
#cp $PARFILE $PARFILE.imp

rm -f $PARFILE
echo $PARFILE

rm -f $TempFile
}

#---------------------------------------------
#	call to oracle sqlplus utility
#---------------------------------------------
echo "Please wait, copying..."

CopyTable 2>&1  | grep 'working area'
