#!/opt/perl5/bin/perl
#******************************************************************************
# (c) COPYRIGHT 1996 ANDERSEN CONSULTING - ALL RIGHTS RESERVED.
# THIS WORK IS PROTECTED BY COPYRIGHT LAW AS AN UNPUBLISHED WORK.
#
# Copybook sort
#
# Arguments: copybook to sort. Assumes cobol copybook, unless filename ends
#	     in ".h".
#
# Return Codes
#              0  Success
#	       Anything else, failure.
#
# Andersen Consulting - SolutionWorks
#
# Coder           Date      Action
# Lorne Berman    05/15/98  Original Code.
#******************************************************************************

open (FILE, "@ARGV[0]") or die ("Error: Cannot open file \"@ARGV[0]\"\n\nUSAGE:\n\t$0 <copybook name> [ > <new filename> ]\n\n");

if (@ARGV[0] =~ /\.h$/) {
	$cobol = 0;
} else {
	$cobol = 1;
}

$contline = 0;
$valline = "";
@vallist = ();
$numline = 0;
$started = 0;

while ($line = <FILE>) 
{

	if ((!$cobol and $line =~ /^#define /) or (!$cobol and $line =~ /^#ifndef /) or ($cobol and $line =~ /^ *88 /) or $contline) 
        {
		$nocontline = 1 if ((!$cobol and $line =~ /^#define /) and (!$contline));

		$started = 1;
		$filearray[$numline] = $line;	

		$snumline = $numline unless ($contline);

		foreach (split (/,/,$line)) 
                {
			$valline = $valline.$1 if ($cobol and /'(.*)'/);
			$valline = $valline.$1 if (!$cobol and /"(.*)"/);
		}

		# if line ends with ".", then we have the completed line, otherwise, its a continuation.
		if (($nocontline) or (!$cobol and $line =~ /\#endif\s*/) or ($cobol and $line =~ /\.\s*/)) 
                {
			$contline = 0;
                        $valline = $valline.$numline;
			$vallist[scalar(@vallist)] = $valline;
			$slinearray{"$valline"} = $snumline;
			$elinearray{"$valline"} = $numline;
			$valline = "";
		} 
                else 
                {
			$contline = 1;
		}

		$nocontline = 0;
	}

	print "$line" unless $started;
	$numline++;
}

@vallist = sort (@vallist);

foreach (@vallist) 
{

	for ($i = $slinearray{"$_"}; $i <= $elinearray{"$_"}; $i++) 
        {
		print $filearray[$i];
	}
}
