#!/bin/ksh

#############################################################################
#
#	File: deletetb
#
#	Description: It deletes a specific table from the user area      
#
#############################################################################

#--------------------------------------------
#	check input arguments
#--------------------------------------------
if [ ! "$1" ]; then
	echo "\n*** error: missing table name"
	echo "format: \$ deletetb <tablename> <source area>\n"
	exit 0
fi

if [ ! "$2" ]; then
	echo "\n*** error: missing table name"
	echo "format: \$ deletetb <tablename> <source area>\n"
	exit 0
fi

#--------------------------------------------
#	assign variable values
#--------------------------------------------
ObjectName=$1			# table name is supplied as argument 1
FromArea=$2
FromDatabase=$ORACLE_SID	# database link


#---------------------------------------------
#	function to delete table 
#---------------------------------------------
DeleteTable ()
{
sqlplus $SW_USER/$SW_PASSWORD <<END
drop table $FromArea.$ObjectName;
drop synonym $FromArea.$ObjectName;
drop sequence $FromArea.$ObjectName;
END
}

#---------------------------------------------
#	call to oracle sqlplus utility
#---------------------------------------------
DeleteTable | awk '
	/dropped/ ||
	/ORA-/				{ print $0 }
	'
