#!/bin/ksh 
###########################################################################################
# ScriptName :  archfind
# Description:  This script does a find in the host architecture area.
# Usage      :  devfind <file name>
#               options:
#
# Date       Programmer         Action
# --------------------------------------------
# 3/18/98    Scott Shepherd     Original code
###########################################################################################

if [[ $# != 1 ]]; then
    print "USAGE: devfind <file name>"
    exit 1
fi

find $BASE_TOOL -name "$1*" |grep -v "/archives/"
