#!/bin/ksh
# SCCS: printit  1.1  01/09/95  17:04:01
#**************************************************************************
#	Name  		:	printit
#
#	Arguments	:	<a file in the current directory>
#
#	Description	:	Prints two pages to a regular page in landscape format.
#					Note that if the filename is not in the current directory
#					the file will still print, but the path printed on the
#					document will be inaccurate.
#
#**************************** Revision History ****************************
# Date		Programmer		Action/Description
# --------	--------------------- 	-----------------------------------
# 01/09/95	Abraham Palmer			Original Code.
# --------	---------------------	-----------------------------------
#**************************************************************************
expand -t4 $1 | pr -h"$(pwd)/$1  " -l66 | lpr -onb -ohalf
