#!/bin/sh
# This script resets the quickstart tables for a given program.

if [[ m"$1" = m ]]
then
	echo 'Type program name to reset RSAM/Quickstart for, enter to quit. (ex. CUBGM033)'
	read dummy
else
	dummy="$1"
fi

# Convert dummy to uppercase
touch "conv.$dummy"
toupper.ksh -e "conv.$dummy" > /dev/null 2>/dev/null
dummy=`ls conv.* | cut -d'.' -f2-80`
rm conv.*

if [[ m"$dummy" != m ]]
then

rm *.ckp > /dev/null 2>/dev/null
rm ~/tmp*  > /dev/null 2>/dev/null
sqlplus $SW_USER/$SW_PASSWORD << end
update swrstb03 set TX_INTERNAL=' ' where KY_PGM_ID = '$dummy';
update bmcqso_ckptcntl set CKPTCNTL_INTERNAL=' ' where CKPTCNTL_PGM = '$dummy';
end

fi
