#!/bin/ksh
########################################################################### 
#
#	File: revokedb
#
#	Description: revokes permissions to all tables
#		     within an Application_Owner
#
########################################################################### 

#----------------------------------------
#	get data from user
#----------------------------------------
echo "\nEnter OWNER's id: (i.e. c1_base_unit, c1_base_system, etc...)"
read OWNER

# echo "Enter OWNER's password:"
# read OWNER_PASSWORD

echo "Enter permission: (i.e. select, "select, insert, update", all, etc...)"
read PERMISION

# echo "Enter GRANTEE id: (i.e. public, <userid>, or <role>)"
# read GRANTEE

OWNER_PASSWORD=$OWNER
GRANTEE=public

#----------------------------------------
#	set variables     
#----------------------------------------
TBLROWTAG="~~table"

#----------------------------------------
#	function to create table list
#----------------------------------------
CreateTableList ()
{
sqlplus $OWNER/$OWNER <<END
select '$TBLROWTAG', table_name from user_tables;
select '$TBLROWTAG', view_name from user_views;
select '$TBLROWTAG', sequence_name from user_sequences;
END
}

#----------------------------------------
#	function to revoke permision 
#----------------------------------------
RevokePermision ()
{
echo "object: $TNAME"
sqlplus $OWNER/$OWNER_PASSWORD <<END
revoke $PERMISION on $OWNER.$TNAME from $GRANTEE;
END
}

#----------------------------------------
#	main
#----------------------------------------
CreateTableList | while read TAG TNAME
do
if [ "$TAG" = "$TBLROWTAG" ]; then	# if this line is a table
	RevokePermision | awk '
		/ORA-/ ||
		/Revoke/ ||
		/object:/	{ print $0 }
		'
fi
done
